import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        ink:          'rgb(var(--ink) / <alpha-value>)',
        'ink-muted':  'rgb(var(--ink) / 0.6)',
        paper:        'rgb(var(--paper) / <alpha-value>)',
        'paper-dark': 'rgb(var(--paper-dark) / <alpha-value>)',
        accent:       'rgb(var(--accent) / <alpha-value>)',
        'accent-soft':'rgb(var(--accent) / 0.08)',
        rule:         'rgb(var(--ink) / 0.15)',
        "on-background": "#1a1c1b",
        "inverse-primary": "#ffb596",
        "on-tertiary-container": "#fefcfb",
        "inverse-surface": "#2f3130",
        "surface-dim": "#dadad8",
        primary: "#d4622a",
        "secondary-fixed": "#e5e2e1",
        "outline-variant": "#dec0b5",
        "on-surface": "#1a1c1b",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "on-secondary-container": "#636262",
        "surface-variant": "#e2e3e1",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffdbcd",
        tertiary: "#5c5c5c",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "primary-container": "#c0541c",
        "surface-container": "#eeeeec",
        "on-tertiary-fixed": "#1b1c1c",
        "surface-container-high": "#e8e8e6",
        "secondary-fixed-dim": "#c8c6c5",
        "secondary-container": "#e2dfde",
        "on-error": "#ffffff",
        "on-surface-variant": "#57423a",
        "primary-fixed-dim": "#ffb596",
        "on-secondary-fixed": "#1c1b1b",
        outline: "#8b7268",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#474747",
        "tertiary-container": "#757474",
        "surface-tint": "#a33e03",
        "inverse-on-surface": "#f1f1ef",
        "tertiary-fixed-dim": "#c8c6c6",
        secondary: "#5f5e5e",
        "on-secondary-fixed-variant": "#474746",
        "on-primary-fixed-variant": "#7d2d00",
        error: "#ba1a1a",
        "on-primary-container": "#fffbff",
        "tertiary-fixed": "#e4e2e1",
        background: "#f9f9f7",
        "surface-container-highest": "#e2e3e1",
        "on-primary-fixed": "#360f00",
        surface: "#f9f9f7",
        "surface-bright": "#f9f9f7",
        "surface-container-low": "#f4f4f2",
        "editorial-maroon": "#7d0a21",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Newsreader", "serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Plus Jakarta Sans", "sans-serif"],
        sans: ["Plus Jakarta Sans", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
